<template>
    <div class="shadow mb-10 font-text">
        <header class="py-8 font-bold flex justify-between">
          <nuxt-link to="/">
            <h1 class="text-focus-in title text-3xl ml-20 border-white border-b-2">GiveMeSnack</h1>
          </nuxt-link>
          <nav class="nav work-mode text-2xl mr-20" v-if = this.work.situation >
            <img src="../assets/photo/round_laptop_white_24dp.png" alt="" class="mode-icon">
            勤務中
          </nav>
          <nav class="nav break-mode text-2xl mr-20" v-else>
            <img src="../assets/photo/round_coffee_white_24dp.png" alt="" class="mode-icon">
            休憩中
          </nav>
        </header>
    </div>
</template>

<script>
export default {
  setup() {
  },
  data(){
    return {
      work: {
        now_time_str:'',
        rest_time:50,
        now_time:0,
        situation:true,
      },
      show: false,
    }
  },
  methods: {
    async get_situation(){
      var d = new Date();
      var mm = ('0' + d.getMinutes()).slice(-2);
      this.work.now_time_str =mm;
      this.work.now_time = Number(this.work.now_time_str);
      if(this.work.now_time >= this.work.rest_time){
        this.work.situation = false;
      }
    }
  },

  async mounted(){
    await this.get_situation();
  },
}
</script>

<style>
header {
  width: 100%;
  background-color: #573a2e;
  color: white;
}

.mode-icon {
  display: inline;
}
 
.menu-item {
  list-style: none;
  display: inline-block;
  padding: 10px;
}

@media screen and (max-width: 600px) {
  header h1 {
    font-size: 6vw !important;
    margin-left: 10vw !important;
  }

  header nav {
    font-size: 4vw !important;
    margin-right: 10vw !important;
  }
}

.text-focus-in {
  -webkit-animation: text-focus-in 1.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
          animation: text-focus-in 1.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-11-27 15:52:19
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
</style>